Algoritmo "Taboada"
// Descrição   : Esse programa mostra a Taboada de 9 ...

var
// Seção de Declarações das variáveis 
   i : inteiro
   x : caracter
inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    LIMPATELA
    ESCREVAL(" ")
    ESCREVA("Digite o seu nome : ")
    LEIA(X)
    ESCREVAL(" TABOADA DE NOVE (09) ")
    PARA i DE 1 ATÉ 10 FAÇA
        ESCREVAL(i," X 9 = ",i * 9)
    FIMPARA
    
fimalgoritmo
